function(set_cxx_flags)
     set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} ${ARGN} PARENT_SCOPE)
endfunction()

include(CheckCXXCompilerFlag)
function(enable_max_cxx_standard)
     check_cxx_compiler_flag(-std=c++11 CXX_STD_11)
     check_cxx_compiler_flag(-std=c++14 CXX_STD_14)
     check_cxx_compiler_flag(-std=c++17 CXX_STD_17)
     check_cxx_compiler_flag(-std=c++20 CXX_STD_20)
     if(CXX_STD_20)
          add_definitions(-std=c++20)
     elseif(CXX_STD_17)
          add_definitions(-std=c++17)
     elseif(CXX_STD_14)
          add_definitions(-std=c++14)
     elseif(CXX_STD_11)
          add_definitions(-std=c++11)
     endif()
endfunction()